env:
  TURBO_API: "http://127.0.0.1:8585"
  TURBO_TEAM: "zed-ramblers-media-website-build"
  # The value of TURBO_TOKEN will be checked by the cache server
  TURBO_TOKEN: "secret-turbo-token"

on:
  pull_request:
  push:
    branches: [main, feature/*]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: self test action
      uses: ./
    # after checking out your code
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Turborepo Cache Server
      # ALWAYS use a pinned version of the action
      # As we don't ship the latest versions of the binary on the main branch
      # PLEASE see the latest versions here:
      # https://github.com/brunojppb/turbo-cache-server/releases
      uses: brunojppb/turbo-cache-server@2.0.2
      env:
        PORT: "8585"
        S3_BUCKET_NAME: ramblers-media-turborepo
        # Region defaults to "eu-central-1"
        S3_REGION: "us-west-2"
        # Optional: If you need to provide specific auth keys, separate from default AWS credentials
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        # Optional: If not using AWS, provide endpoint like `https://minio` for your instance.
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        # Optional: If your S3-compatible store does not support requests
        # like https://bucket.hostname.domain/. Setting `S3_USE_PATH_STYLE`
        # to true configures the S3 client to make requests like
        # https://hostname.domain/bucket instead.
        # Defaults to "false"
        S3_USE_PATH_STYLE: false
        # Max payload size for each cache object sent by Turborepo
        # Defaults to 100 MB
        # Requests larger than that, will get "HTTP 413: Entity Too Large" errors
        MAX_PAYLOAD_SIZE_IN_MB: "100"

    # Now you can run your turborepo tasks and rely on the cache server
    # available in the background to provide previously built artifacts (cache hits)
    # and let Turborepo upload new artifacts when there is a cache miss.
    - name: Run tasks
      run: turbo run test build typecheck